### PR TITLE
Deprecate deadlineWith and add deadlineFor instead

### PR DESCRIPTION
**Pull request by spacey-sooty**
From https://github.com/wpilibsuite/allwpilib/pull/6544

### CODE REVIEW

**Comment by TheTripleV** [comment]
needs a test. You can copy and paste the existing deadlineWith one.

**Comment by virtuald** [comment]
[`git-source-track`](https://github.com/virtuald/git-source-track) information needs to be updated too, probably should add it to CI and a document for how one does that.

**Comment by spacey-sooty** [comment]
> needs a test. You can copy and paste the existing deadlineWith one.

Should I delete the deadlineWith one as well?

**Comment by TheTripleV** [comment]
Keep it for now since its still supported

**Pull request merged**
